spring:
  application:
    name: inventory-service
  zipkin:
    enabled: false

  datasource:
    url: jdbc:h2:mem:testdb;MODE=MYSQL
  h2:
    console:
      enabled: true

  security:
    user:
      name: good
      password: beer

  # Spring Data hangs when not set under Spring Boot 2.3.0
  data:
    jpa:
      repositories:
        bootstrap-mode: default

  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-date-timestamps-as-nanoseconds: true

logging:
  level:
    prv.jws: debug

server:
  port: 8082
